-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 8aa14d218d0fe5a2c486498269b3e37d3ba5aad2
    hooks:
    -   id: pyflakes
        files: \.py$
    -   id: debug-statements
        files: \.py$
    -   id: trailing-whitespace
        files: \.(py|sh|yaml)$
    -   id: name-tests-test
        files: tests/.+\.py$
    -   id: end-of-file-fixer
        files: \.(py|sh|yaml)$
-   repo: git@github.com:pre-commit/pre-commit
    sha: c695ee9a9a78ac73439c52e0085bafec8037bc2d
    hooks:
    -   id: validate_manifest
        files: ^manifest.yaml$
    -   id: validate_config
        files: ^\.pre-commit-config.yaml$
