-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 84fbf05803f25fea2ad4a9509b3666840bf580b4
    hooks:
    -   id: trailing-whitespace
        files: \.(py|sh|yaml)$
    -   id: end-of-file-fixer
        files: \.(py|sh|yaml)$
    -   id: check-yaml
        files: \.(yaml|yml)$
    -   id: debug-statements
        files: \.py$
    -   id: name-tests-test
        files: tests/.+\.py$
    -   id: pyflakes
        files: \.py$
-   repo: git@github.com:pre-commit/pre-commit
    sha: 3cfc49b522dee27cdcce83781cd874c5638ad6c1
    hooks:
    -   id: validate_config
        files: ^\.pre-commit-config.yaml$
    -   id: validate_manifest
        files: ^hooks.yaml$
        exclude: ^$
