environment:
    matrix:
        - TOXENV: py27
        - TOXENV: py34

install:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install tox

# Not a C# project
build: false

before_test:
  - git config --global user.name "AppVeyor CI"
  - git config --global user.email "user@example.com"

# Workaround for http://help.appveyor.com/discussions/problems/1531-having-issues-with-configured-git-bash
test_script: bash -c tox
