
-
    repo: git@github.com:pre-commit/pre-commit-hooks
    sha: cd74dc150c142c3be70b24eaf0b02cae9d235f37
    hooks:
        -
            id: pyflakes
            files: '\.py$'
        -
            id: jslint
            files: '\.js$'
        -
            id: trim_trailing_whitespace
            files: '\.py$'
