-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: bec87f6c87284ea15dbcf7801810404c8036bab4
    hooks:
    -   id: pyflakes
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: end-of-file-fixer
-   repo: git@github.com:pre-commit/pre-commit
    sha: c62c1a3b513ab9e057e85a5e950bd7c438371076
    hooks:
    -   id: validate_manifest
    -   id: validate_config
